package com.edisonsolar.businesspro;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.*;
import android.graphics.pdf.PdfDocument;
import android.location.*;
import android.net.Uri;
import android.os.*;
import android.provider.MediaStore;
import android.view.*;
import android.widget.*;
import androidx.core.app.ActivityCompat;
import androidx.core.content.ContextCompat;
import androidx.core.content.FileProvider;
import java.io.*;
import java.text.SimpleDateFormat;
import java.util.*;

public class MainActivity extends Activity {
    DBHelper db; LinearLayout root; Project photoProject; Uri cameraUri;
    final int BLUE=Color.rgb(11,94,215), GREEN=Color.rgb(25,135,84), ORANGE=Color.rgb(240,138,36), PURPLE=Color.rgb(111,66,193), RED=Color.rgb(220,53,69), DARK=Color.rgb(23,50,77), BG=Color.rgb(245,249,253);
    int dp(int n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
    @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.WHITE);getWindow().setNavigationBarColor(Color.WHITE);db=new DBHelper(this);home();}
    TextView txt(String s,float z,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(DARK);t.setTypeface(null,bold?1:0);t.setPadding(dp(8),dp(7),dp(8),dp(7));return t;}
    EditText field(String hint,String val){EditText e=new EditText(this);e.setHint(hint);e.setText(val);e.setTextSize(17);e.setTextColor(DARK);e.setHintTextColor(Color.GRAY);e.setPadding(dp(12),dp(5),dp(12),dp(5));e.setSingleLine(false);return e;}
    Button button(String s,int color,View.OnClickListener l){Button b=new Button(this);b.setText(s);b.setTextSize(17);b.setTypeface(null,1);b.setTextColor(Color.WHITE);b.setAllCaps(false);b.setGravity(Gravity.CENTER);b.setMinHeight(dp(60));b.setOnClickListener(l);GradientDrawableCompat(b,color);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(62));p.setMargins(dp(4),dp(7),dp(4),dp(7));b.setLayoutParams(p);return b;}
    void GradientDrawableCompat(Button b,int c){android.graphics.drawable.GradientDrawable g=new android.graphics.drawable.GradientDrawable();g.setColor(c);g.setCornerRadius(dp(16));b.setBackground(g);}
    TextView card(String s){TextView t=txt(s,17,true);t.setBackgroundColor(Color.WHITE);t.setPadding(dp(14),dp(12),dp(14),dp(12));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(dp(4),dp(6),dp(4),dp(6));t.setLayoutParams(p);return t;}
    void page(String title){ScrollView sc=new ScrollView(this);sc.setFillViewport(true);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(12),dp(14),dp(12),dp(28));root.setBackgroundColor(BG);LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);Button back=new Button(this);back.setText("←");back.setTextSize(30);back.setTextColor(DARK);back.setBackgroundColor(Color.TRANSPARENT);back.setOnClickListener(v->home());h.addView(back,new LinearLayout.LayoutParams(dp(58),dp(64)));TextView t=txt(title,24,true);h.addView(t,new LinearLayout.LayoutParams(0,dp(64),1));root.addView(h);sc.addView(root);setContentView(sc);}
    void home(){page("EDISON SOLAR MANAGER PRO");ImageView im=new ImageView(this);int id=getResources().getIdentifier("edison_solar_logo","drawable",getPackageName());if(id!=0)im.setImageResource(id);im.setAdjustViewBounds(true);im.setScaleType(ImageView.ScaleType.CENTER_INSIDE);root.addView(im,new LinearLayout.LayoutParams(-1,dp(150)));root.addView(card(db.dashboard()));root.addView(button("🏢  Companies",BLUE,v->companies()));root.addView(button("☀️  Projects",BLUE,v->projects()));root.addView(button("👷  Workers / Attendance",PURPLE,v->workers()));root.addView(button("💰  Payment Collection",GREEN,v->payments()));root.addView(button("🧾  Expenses",ORANGE,v->expenses()));root.addView(button("📅  Calendar",PURPLE,v->calendar()));root.addView(button("📊  Reports / PDF",PURPLE,v->reports()));}
    void companies(){page("Companies");root.addView(button("+  Add Company",BLUE,v->companyDialog(null)));for(Company c:db.companies()){root.addView(card(c.name+"\nPhone: "+c.phone+"\nProjects: "+countProjects(c.id)+" | kW: "+fmt(companyKw(c.id))));LinearLayout r=new LinearLayout(this);r.addView(button("Edit",BLUE,v->companyDialog(c)),new LinearLayout.LayoutParams(0,dp(58),1));r.addView(button("Delete",RED,v->{confirm("Delete company?",()->{db.deleteCompany(c.id);companies();});}),new LinearLayout.LayoutParams(0,dp(58),1));root.addView(r);}}
    int countProjects(int id){android.database.Cursor c=db.getReadableDatabase().rawQuery("SELECT COUNT(*) FROM projects WHERE company_id=?",new String[]{""+id});int x=c.moveToFirst()?c.getInt(0):0;c.close();return x;}
    double companyKw(int id){return q("SELECT COALESCE(SUM(kw),0) FROM projects WHERE company_id=?",id);}
    double q(String sql,int id){android.database.Cursor c=db.getReadableDatabase().rawQuery(sql,new String[]{""+id});double x=c.moveToFirst()?c.getDouble(0):0;c.close();return x;}
    double fmtN(String s){try{return Double.parseDouble(s.trim());}catch(Exception e){return 0;}}
    String fmt(double x){return DBHelper.fmt(x);}
    void companyDialog(Company old){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);EditText n=field("Company Name",old==null?"":old.name),p=field("Phone",old==null?"":old.phone);l.addView(n);l.addView(p);AlertDialog d=new AlertDialog.Builder(this).setTitle(old==null?"Add Company":"Edit Company").setView(l).setNegativeButton("Cancel",null).setPositiveButton("Save",null).create();d.setOnShowListener(x->d.getButton(-1).setOnClickListener(v->{if(n.getText().toString().trim().isEmpty()){n.setError("Required");return;}if(old==null)db.addCompany(n.getText().toString(),p.getText().toString());else db.updateCompany(old.id,n.getText().toString(),p.getText().toString());d.dismiss();companies();}));d.show();}
    void projects(){page("Projects");root.addView(button("+  Add Project",BLUE,v->projectDialog(null)));for(Project p:db.projects()){root.addView(card(p.number+" • "+p.customer+"\nCompany: "+p.company+"\n"+fmt(p.kw)+" kW • ₹"+fmt(p.amount)+"\nSite: "+p.site+"\nCollected ₹"+fmt(db.collection(p.id))+" • Pending ₹"+fmt(db.pending(p.id))));root.addView(button("Open / Edit / Details",BLUE,v->projectMenu(p)));}}
    void projectDialog(Project old){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);EditText co=field("Company",old==null?"":old.company),cu=field("Customer",old==null?"":old.customer),ph=field("Phone",old==null?"":old.phone),si=field("Site",old==null?"":old.site),kw=field("Solar kW",old==null?"":""+old.kw),am=field("Amount",old==null?"":""+old.amount),da=field("Date",old==null?today():old.date),st=field("Status",old==null?"Pending":old.status),wo=field("Work Detail",old==null?"":old.work);for(EditText e:new EditText[]{co,cu,ph,si,kw,am,da,st,wo})l.addView(e);AlertDialog d=new AlertDialog.Builder(this).setTitle(old==null?"Add Project":"Edit Project").setView(l).setNegativeButton("Cancel",null).setPositiveButton("Save",null).create();d.setOnShowListener(x->d.getButton(-1).setOnClickListener(v->{if(old==null)db.addProject(0,co.getText().toString(),cu.getText().toString(),ph.getText().toString(),si.getText().toString(),fmtN(kw.getText().toString()),fmtN(am.getText().toString()),da.getText().toString(),st.getText().toString(),wo.getText().toString());else db.updateProject(old,old.companyId,co.getText().toString(),cu.getText().toString(),ph.getText().toString(),si.getText().toString(),fmtN(kw.getText().toString()),fmtN(am.getText().toString()),da.getText().toString(),st.getText().toString(),wo.getText().toString());d.dismiss();projects();}));d.show();}
    void projectMenu(Project p){String[] a={"Edit Project","Payments","Expenses","Photos","GPS / Map","PDF","WhatsApp","Delete"};new AlertDialog.Builder(this).setTitle(p.customer).setItems(a,(d,w)->{if(w==0)projectDialog(p);else if(w==1)projectPayments(p);else if(w==2)projectExpenses(p);else if(w==3)photos(p);else if(w==4)gps(p);else if(w==5)pdf(p);else if(w==6)share(projectReport(p));else confirm("Delete project?",()->{db.deleteProject(p.id);projects();});}).show();}
    String projectReport(Project p){return "EDISON SOLAR MANAGER PRO\n\nProject: "+p.number+"\nCompany: "+p.company+"\nCustomer: "+p.customer+"\nPhone: "+p.phone+"\nSite: "+p.site+"\nSolar: "+fmt(p.kw)+" kW\nAmount: ₹"+fmt(p.amount)+"\nCollection: ₹"+fmt(db.collection(p.id))+"\nPending: ₹"+fmt(db.pending(p.id))+"\nExpenses: ₹"+fmt(db.expenses(p.id))+"\nProfit: ₹"+fmt(db.profit(p.id))+"\nDate: "+p.date+"\nStatus: "+p.status+"\nWork: "+p.work;}
    void projectPayments(Project p){page("Payments");root.addView(card("Project: "+p.customer+"\nAmount ₹"+fmt(p.amount)+"\nCollected ₹"+fmt(db.collection(p.id))+"\nPending ₹"+fmt(db.pending(p.id))));root.addView(button("+ Add Payment",GREEN,v->paymentDialog(p)));}
    void paymentDialog(Project p){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);EditText a=field("Amount",""),n=field("Note","");l.addView(a);l.addView(n);new AlertDialog.Builder(this).setTitle("Add Payment").setView(l).setNegativeButton("Cancel",null).setPositiveButton("Save",(d,w)->{db.addPayment(p.id,fmtN(a.getText().toString()),today(),n.getText().toString());projectPayments(p);}).show();}
    void payments(){page("Payment Collection");for(Project p:db.projects()){root.addView(card(p.number+" • "+p.customer+"\nCollected ₹"+fmt(db.collection(p.id))+"\nPending ₹"+fmt(db.pending(p.id))));root.addView(button("Add Payment",GREEN,v->paymentDialog(p)));}}
    void projectExpenses(Project p){page("Expenses");root.addView(card("Project: "+p.customer+"\nExpenses ₹"+fmt(db.expenses(p.id))+"\nProfit ₹"+fmt(db.profit(p.id))));root.addView(button("+ Add Expense",ORANGE,v->expenseDialog(p)));}
    void expenseDialog(Project p){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);EditText a=field("Amount",""),c=field("Expense Type","Other"),n=field("Note","");l.addView(a);l.addView(c);l.addView(n);new AlertDialog.Builder(this).setTitle("Add Expense").setView(l).setNegativeButton("Cancel",null).setPositiveButton("Save",(d,w)->{db.addExpense(p.id,fmtN(a.getText().toString()),c.getText().toString(),today(),n.getText().toString());projectExpenses(p);}).show();}
    void expenses(){page("Expenses");for(Project p:db.projects())root.addView(card(p.number+" • "+p.customer+"\nExpenses ₹"+fmt(db.expenses(p.id))+"\nProfit ₹"+fmt(db.profit(p.id))));}
    void workers(){page("Workers / Attendance");root.addView(button("+ Add Worker",PURPLE,v->workerDialog(null)));for(Worker w:db.workers()){String m=new SimpleDateFormat("yyyy-MM",Locale.getDefault()).format(new Date());root.addView(card("👷 "+w.name+"\nPresent: "+db.presentDays(w.id,m)+"  Absent: "+db.absentDays(w.id,m)+"\nDaily: ₹"+fmt(w.dailySalary)+"  Monthly: ₹"+fmt(w.monthlySalary)+"\nAdvance: ₹"+fmt(db.advances(w.id))+"\nBalance: ₹"+fmt(db.salaryBalance(w,m))));root.addView(button("✏️ Edit Worker",BLUE,v->workerDialog(w)));root.addView(button("📅 Attendance",GREEN,v->attendanceDialog(w)));root.addView(button("💵 Advance",ORANGE,v->advanceDialog(w)));root.addView(button("🗑 Delete Worker",RED,v->confirm("Delete worker?",()->{db.deleteWorker(w.id);workers();})));}root.addView(button("📄 Salary PDF / WhatsApp",PURPLE,v->salaryShare()));}
    void workerDialog(Worker old){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);EditText n=field("Worker Name",old==null?"":old.name),p=field("Phone",old==null?"":old.phone),d=field("Daily Salary",old==null?"":""+old.dailySalary),m=field("Monthly Salary",old==null?"":""+old.monthlySalary);l.addView(n);l.addView(p);l.addView(d);l.addView(m);new AlertDialog.Builder(this).setTitle(old==null?"Add Worker":"Edit Worker").setView(l).setNegativeButton("Cancel",null).setPositiveButton("Save",(x,y)->{Worker w=old==null?new Worker():old;w.name=n.getText().toString();w.phone=p.getText().toString();w.dailySalary=fmtN(d.getText().toString());w.monthlySalary=fmtN(m.getText().toString());db.saveWorker(w);workers();}).show();}
    void attendanceDialog(Worker w){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);EditText date=field("Date YYYY-MM-DD",todayISO()),site=field("Project / Site",""),status=field("Present / Absent","Present");l.addView(date);l.addView(status);l.addView(site);new AlertDialog.Builder(this).setTitle("Add / Edit Attendance").setView(l).setNegativeButton("Cancel",null).setPositiveButton("Save",(d,x)->{saveAttendanceRaw(w.id,date.getText().toString(),status.getText().toString(),site.getText().toString());workers();}).show();}
    void saveAttendanceRaw(int wid,String date,String status,String site){android.content.ContentValues v=new android.content.ContentValues();v.put("worker_id",wid);v.put("date",date);v.put("status",status);v.put("site",site);v.put("note","");db.getWritableDatabase().insertWithOnConflict("attendance",null,v,android.database.sqlite.SQLiteDatabase.CONFLICT_REPLACE);}
    void advanceDialog(Worker w){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);EditText a=field("Advance Amount",""),d=field("Date YYYY-MM-DD",todayISO()),n=field("Note","");l.addView(a);l.addView(d);l.addView(n);new AlertDialog.Builder(this).setTitle("Salary Advance").setView(l).setNegativeButton("Cancel",null).setPositiveButton("Save",(x,y)->{db.saveAdvance(w.id,fmtN(a.getText().toString()),d.getText().toString(),n.getText().toString());workers();}).show();}
    String today(){return new SimpleDateFormat("dd-MM-yyyy",Locale.getDefault()).format(new Date());}
    String todayISO(){return new SimpleDateFormat("yyyy-MM-dd",Locale.getDefault()).format(new Date());}
    void salaryShare(){String m=new SimpleDateFormat("yyyy-MM",Locale.getDefault()).format(new Date());StringBuilder s=new StringBuilder("EDISON SOLAR WORKER SALARY REPORT\nMonth: "+m+"\n\n");for(Worker w:db.workers())s.append(db.workerReport(w,m)).append("\n\n");share(s.toString());}
    void calendar(){page("Calendar");root.addView(button("📅 Select Date",PURPLE,v->{Calendar c=Calendar.getInstance();new DatePickerDialog(this,(x,y,m,d)->calendarDay(String.format(Locale.getDefault(),"%02d-%02d-%04d",d,m+1,y)),c.get(1),c.get(2),c.get(5)).show();}));}
    void calendarDay(String date){page("Work • "+date);boolean found=false;for(Project p:db.projects())if(date.equals(p.date)){found=true;root.addView(card(p.number+"\n"+p.company+"\n"+p.customer+"\n"+p.site+"\n"+fmt(p.kw)+" kW\n"+p.status));}if(!found)root.addView(card("No project on this date."));}
    void reports(){page("Reports / PDF");root.addView(card(db.dashboard()));for(Project p:db.projects())root.addView(button("📄 PDF "+p.number,PURPLE,v->pdf(p)));root.addView(button("📱 WhatsApp / Share",GREEN,v->share(db.dashboard())));}
    void photos(Project p){photoProject=p;page("Photos / Gallery");root.addView(card(p.customer+"\nSaved Photos: "+db.photos(p.id).size()));root.addView(button("📷 Take Photo",BLUE,v->takePhoto()));root.addView(button("🖼 Open Gallery",PURPLE,v->openGallery()));}
    void takePhoto(){if(ContextCompat.checkSelfPermission(this,Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED){ActivityCompat.requestPermissions(this,new String[]{Manifest.permission.CAMERA},101);return;}try{File dir=getExternalFilesDir(Environment.DIRECTORY_PICTURES);if(!dir.exists())dir.mkdirs();File f=new File(dir,"EDISON_"+System.currentTimeMillis()+".jpg");cameraUri=FileProvider.getUriForFile(this,getPackageName()+".fileprovider",f);Intent i=new Intent(MediaStore.ACTION_IMAGE_CAPTURE);i.putExtra(MediaStore.EXTRA_OUTPUT,cameraUri);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION);startActivityForResult(i,101);}catch(Exception e){Toast.makeText(this,e.toString(),Toast.LENGTH_LONG).show();}}
    void openGallery(){startActivityForResult(new Intent(Intent.ACTION_PICK,MediaStore.Images.Media.EXTERNAL_CONTENT_URI),102);}
    @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(c!=RESULT_OK)return;if(r==101&&photoProject!=null&&cameraUri!=null){db.addPhoto(photoProject.id,cameraUri.toString());photos(photoProject);}else if(r==102&&d!=null&&d.getData()!=null&&photoProject!=null){db.addPhoto(photoProject.id,d.getData().toString());photos(photoProject);}}
    void gps(Project p){if(ContextCompat.checkSelfPermission(this,Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED){ActivityCompat.requestPermissions(this,new String[]{Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACCESS_COARSE_LOCATION},100);return;}LocationManager lm=(LocationManager)getSystemService(LOCATION_SERVICE);try{Location l=lm.getLastKnownLocation(LocationManager.GPS_PROVIDER);if(l==null)l=lm.getLastKnownLocation(LocationManager.NETWORK_PROVIDER);if(l==null){Toast.makeText(this,"Turn on GPS",Toast.LENGTH_LONG).show();return;}startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("geo:"+l.getLatitude()+","+l.getLongitude()+"?q="+l.getLatitude()+","+l.getLongitude())));}catch(Exception e){Toast.makeText(this,"Map unavailable",Toast.LENGTH_LONG).show();}}
    void pdf(Project p){PdfDocument doc=new PdfDocument();try{PdfDocument.Page pg=doc.startPage(new PdfDocument.PageInfo.Builder(595,842,1).create());Paint paint=new Paint();paint.setTextSize(13);float y=45;for(String line:projectReport(p).split("\n")){if(y>800)break;pg.getCanvas().drawText(line,40,y,paint);y+=22;}doc.finishPage(pg);File dir=new File(getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS),"EDISON_SOLAR");if(!dir.exists())dir.mkdirs();File f=new File(dir,p.number+"_Report.pdf");FileOutputStream out=new FileOutputStream(f);doc.writeTo(out);out.close();Uri u=FileProvider.getUriForFile(this,getPackageName()+".fileprovider",f);Intent i=new Intent(Intent.ACTION_SEND);i.setType("application/pdf");i.putExtra(Intent.EXTRA_STREAM,u);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(i,"Share PDF"));}catch(Exception e){Toast.makeText(this,"PDF Error: "+e.getMessage(),Toast.LENGTH_LONG).show();}finally{doc.close();}}
    void share(String s){Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/plain");i.putExtra(Intent.EXTRA_TEXT,s);startActivity(Intent.createChooser(i,"Share / WhatsApp"));}
    void confirm(String msg,Runnable yes){new AlertDialog.Builder(this).setMessage(msg).setNegativeButton("Cancel",null).setPositiveButton("OK",(d,w)->yes.run()).show();}
}
